wandb_version: 1

model_type:
  desc: null
  value: gpt-nano
batch_size:
  desc: null
  value: 16
block_size:
  desc: null
  value: 11
vocab_size:
  desc: null
  value: 3
pretrained:
  desc: null
  value: false
device:
  desc: null
  value: cpu
max_iters:
  desc: null
  value: 1000
learning_rate:
  desc: null
  value: 0.0001
use_wandb:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1720978220
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.12.4
      5: 0.17.4
      8:
      - 2
      - 5
      13: linux-x86_64
