import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Inference from '../components/Inference'
import Train from '../components/Train'

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>ORT LLM</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={styles.main}>
                <Inference />
                <Train />
            </main>
        </div>
    )
}

export default Home
